# These are supported funding model platforms

github: [quick123official]
patreon: quick123official
open_collective: quick123official
ko_fi: quick123official
liberapay: quick123official
issuehunt: quick123official
otechie: quick123official
custom: ['https://quick123.net/']
